### PR TITLE
Add sort and address name fields

### PR DESCRIPTION
**Pull request by rixx**
- [x] Add new fields to models
- [x] Migrate existing data
- [x] Add new fields to registration forms, including JavaScript magic
- [x] Add new fields to member forms
- [x] Add recalculate magic when config changes
- [ ] Adjust tests

### CODE REVIEW

**Comment by rixx** [comment]
In a next step we can add a "title" field, which would make byro much more suitable to the average DACH area organisation.

**Comment by henryk** [comment]
Good to go in principle.
Though I feel this is leaving the "unopinionated" path. The idea that names can be split into one first name and one last name part is a pretty strong opinion, even in DACH. The only net gain I can see is being able to sort by "last name", and doing so by default. IMHO it could be easier to add a "sort order" column (and have it automatically filled with an algorithmically determined "last" name unless overriden).
That being said, having all fields as `null=True, blank=True` makes most of the problems easy enough to work around, so it's probably ok to merge this.

**Comment by rixx** [comment]
Sorting by last name is one reason, and being able to address people by only first or last name another. Most orgnanisations send out emails to "Hallo {first_name}" or "Sehr geehrte/r Herr/Frau {last_name}", and byro currently only can do "Hallo {full_name}" or "Liebes Mitglied".

A possible alternative would be keeping the name field, and auto-filling a "sort" field and an "personal address" field, but that feels like it would be fairly brittle and annoying to fill in?

At least in the German translation, we could follow the (annoying) standard of translating last_name as Name, so that associations wanting to keep a single name field can do so without problem.

**Comment by henryk** [comment]
Yeah, personally addressing messages is more complicated to do correctly. First/Last name covers neither Rainer Maria Rilke nor María de Zayas y Sotomayor in a useful way. Doing this without generating very bad edge cases would involve fields for a) grammatical gender (trivalue: "Sehr geehrte" vs. "Sehr geehrter" vs. "Sehr geehrte/r"), b) appellation (free form: "Herr", "Frau", "Großherzogin", ...) and c) common name "Rilke". Maybe b and c are the same field.
I once had an address list for the members of the Deutscher Bundestag, with the express purpose to create serial letters. I think it had 6 or so columns for different parts of the name, to cover people like Christian Alexander Freiherr von Stetten.
I believe most of the complexity can be hidden by good UI

**Comment by rixx** [comment]
Hm, okay.

In that case, the correct solution would be to retain the singular name field, and add "address" and "sort_order" fields that get automatically populated, but can be changed manually. The address field in particular would need to be automatically composed out of different fields – either just name, or name and title, depending on a configuration variable.

I'm … not quite sure how to approach this with our generic fields algorithm in a way that makes sense for users.  We would have to be able to include these calculated fields in the registration form. We could, of course, special-case the "name" field and always include those additional fields.

Because, as a user, you just want to enter a name once, in either one or two fields, and then to not touch it again.

**Comment by ilu33** [comment]
There is no universal solution. Names like "Wong Tai Sin" or "Tanaka Shinichi" or any other LastName-FirstName combination will always clash with our usual western naming conventions. So I think the best approach is what makes writing plugins as easy as possible.

The way things are now our plugin (which would include grammatical gender and appellation and whatever else necessary) cannot use the combined field but needs to add separate name fields. To prevent data corruption we have to automatically populate and hide the combined field. I think we mostly managed but it was not easy and we will need to change the views to get our new separate name fields to the top of the page instead of the combined one.

Separate fields are easier to handle for plugins because the plugin can combine them whichever way is necessary. If you want to be "unopinionated" don't put a distinct (first,last)name to those fields. Have 2 or 3 fields for name1, name2, name3 and give them a default sort_order (123) that can be changed (321,132, ...). People could even choose to only use name1 (and leave the rest empty) if they prefer a combined field. That would make transition easy and things really flexible.

**Comment by rixx** [comment]
No, I don't think numbering fields is a good solution. We should either go all-in on "unopinionated" and keep the status quo, or decide on a solution.

Personally, I think the solution that contains a single name field, plus two additional (semi-calculated) fields for "personal address" and "sort order" seems like the closest we can come to flexible and correct.

**Comment by rixx** [comment]
The failing tests seem to be due to #122, merging regardless.

**Pull request merged**
