### PR TITLE
Include liability_interval to determine start date when calculating membership dues

### PR DESCRIPTION
**Pull request by annikahannig**
When calculating memberhship dues, it is no use to include fees that are outside the liability_interval.

### CODE REVIEW

**Comment by lemoer** [comment]
Maybe similar to #120.

**Comment by annikahannig** [comment]
Hey everyone - As I could see it, this was not the conflicting change, (the missing bracket was already in there)

However, a new parameter `_from` was introduced and these changes caused the conflict.
I resolved it - however I did not test it.

**Comment by annikahannig** [comment]
Any news on this?

**Comment by annikahannig** [comment]
I guess we'll then just maintain our fork, as when now all the old stuff is regenerated again this will just end up in chaos.
Thanks though.

**Pull request closed without merging**
