### PR TITLE
add filter for Members with negative balance

### PR DESCRIPTION
**Pull request by oe1rfc**
This adds a filter to the members view for members with negative balance.

I'm not sure how to add a test for this.

### CODE REVIEW

**Comment by rixx** [comment]
That's a very useful addition to byro, thank you!

One minor niggle: queryset methods should return querysets, not lists, so this part would need to change before a merge.

**Comment by oe1rfc** [comment]
Hi, Member.balance is a computed value (via Member._calc_balance()), as far as I know the django ORM it's not possible to directly return a queryset in this case?

**Comment by GoliathLabs** [comment]
@rixx @oe1rfc any updates on this?

**Comment by rixx** [comment]
I don't have push access to this PR, so I'll rebase and merge manually.

(Notably I still think that returning a list is a bit iffy, but I suppose we don't really need to care.)

**Pull request closed without merging**
