### PR TITLE
fixing requirements

### PR DESCRIPTION
**Pull request by bengoshii**
The requirements were incomplete.

### CODE REVIEW

**Comment by rixx** [comment]
We definitely do not require all the packages you added there. Could you expand on which packages you were missing?

**Comment by rixx** [comment]
Also, in addition it would be good if you only pushed changes to the requirements, not unnecessary additional build/config files.

**Comment by rixx** [comment]
Ok, due to lack of response and pushes that don't address the review, I'm closing this PR for now. Feel free to open a new one with only the required changes, though!

**Comment by bengoshii** [comment]
Sorry for the delayed answer (job-related busy). Okay, perhaps there is a misunderstanding of mine. I had to installaded some more packages with pip for making byro executable. I thought this way would be more comfortable for other users.

**Pull request closed without merging**
